---
- name: Simple Utility to Clear the SSSD Cache
  hosts: all
  tasks:
    - name: stop the sssd service
      service:
        name: sssd
        state: stopped

    - name: clear the sssd cache
      command: "sss_cache -E"

    - name: start the sssd service
      service:
        name: sssd
        state: started
